image: docker:stable

services:
  - docker:dind

stages:
  - build
  - test
  - release
  - build_variant
  - test_variant
  - release_variant

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2
  RELEASE_REGISTRY: docker.io
  RELEASE_IMAGE: index.docker.io/$RELEASE_USER

################################################################################
# Templates to avoid repeat. A bit Xtrem here!
# https://docs.gitlab.com/ee/ci/yaml/#anchors
################################################################################

.docker_login_gitlab:
  - &docker_login_gitlab docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com

.docker_pull:
  - &docker_pull docker pull $CI_REGISTRY_IMAGE/$IMAGE || true

.docker_build_push:
  script: &docker_build_push
    - *docker_pull
    - docker build --compress --cache-from $RELEASE_IMAGE/$IMAGE --tag $CI_REGISTRY_IMAGE/$IMAGE $DIR
    - docker push $CI_REGISTRY_IMAGE/$IMAGE

.make_build:
  - &make_build apk --no-cache add make gettext && make build

.test_images: &test_images
  before_script:
    - *docker_login_gitlab
    - *docker_pull

.build_image: &build_image
  stage: build
  before_script:
    - *docker_login_gitlab
    - *make_build
  script: *docker_build_push

.test_drupal8ci: &test_drupal8ci
  stage: test
  <<: *test_images
  script:
    - docker run --rm -t $CI_REGISTRY_IMAGE/$IMAGE /scripts/run-tests.sh

.release: &release
  stage: release
  before_script:
    - docker login -u $RELEASE_USER -p $RELEASE_PASSWORD $RELEASE_REGISTRY
  script:
    - *docker_pull
    - docker tag $CI_REGISTRY_IMAGE/$IMAGE $RELEASE_IMAGE/$IMAGE
    - docker push $RELEASE_IMAGE/$IMAGE
  only:
    - master

.build_variant: &build_variant
  <<: *build_image
  stage: build_variant
  before_script:
    - *docker_login_gitlab
    - *make_build
    - sed -i 's#FROM ${RELEASE_USER}#FROM ${CI_REGISTRY_IMAGE}#g' ${DIR}/Dockerfile

.test_drupal8ci_variant: &test_drupal8ci_variant
  stage: test_variant
  <<: *test_drupal8ci

.release_variant: &release_variant
  stage: release_variant
  <<: *release

################################################################################
# Jobs based on previous templates.
# Only variables need to be changed if needed.
################################################################################

before_script:
  - *docker_login_gitlab
  - *make_build

d8ci:
  <<: *build_image
  variables:
    IMAGE: drupal8ci:8.6
    DIR: '8.6'

t:d8ci:
  <<: *test_drupal8ci
  variables:
    IMAGE: drupal8ci:8.6

r:d8ci:
  <<: *release
  variables:
    IMAGE: drupal8ci:8.6

d8ci-drupal:
  <<: *build_image
  variables:
    IMAGE: drupal8ci:8.6-with-drupal
    DIR: '8.6-with-drupal'

t:d8ci-drupal:
  <<: *test_drupal8ci
  variables:
    IMAGE: drupal8ci:8.6-with-drupal

r:d8ci-drupal:
  <<: *release
  variables:
    IMAGE: drupal8ci:8.6-with-drupal

d8ci-selenium:
  <<: *build_variant
  variables:
    IMAGE: drupal8ci:8.6-selenium
    DIR: '8.6-selenium'

t:d8ci-selenium:
  <<: *test_drupal8ci_variant
  variables:
    IMAGE: drupal8ci:8.6-selenium

r:d8ci-selenium:
  <<: *release_variant
  variables:
    IMAGE: drupal8ci:8.6-selenium

d8ci-drupal-selenium:
  <<: *build_variant
  variables:
    IMAGE: drupal8ci:8.6-with-drupal-selenium
    DIR: '8.6-with-drupal-selenium'

t:d8ci-drupal-selenium:
  <<: *test_drupal8ci_variant
  variables:
    IMAGE: drupal8ci:8.6-with-drupal-selenium

r:d8ci-drupal-selenium:
  <<: *release_variant
  variables:
    IMAGE: drupal8ci:8.6-with-drupal-selenium
