image: docker:stable

services:
  - docker:dind

stages:
  - build
  - test
  - release

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2
  RELEASE_REGISTRY: docker.io
  RELEASE_IMAGE: index.docker.io/$RELEASE_USER

################################################################################
# Templates to avoid repeat. A bit Xtrem here!
# https://docs.gitlab.com/ee/ci/yaml/#anchors
################################################################################

.docker_login_gitlab:
  - &docker_login_gitlab docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com

.docker_pull:
  - &docker_pull docker pull $CI_REGISTRY_IMAGE/$IMAGE || true

.docker_build_push:
  script: &docker_build_push
    - *docker_pull
    - docker build --compress --cache-from $RELEASE_IMAGE/$IMAGE --tag $CI_REGISTRY_IMAGE/$IMAGE $DIR
    - docker push $CI_REGISTRY_IMAGE/$IMAGE

.make_build:
  - &make_build apk --no-cache add make gettext && make build

.build_image: &build_image
  stage: build
  before_script:
    - *docker_login_gitlab
    - *make_build
    - sed -i 's#FROM ${RELEASE_USER}#FROM ${CI_REGISTRY_IMAGE}#g' ${DIR}/Dockerfile
  script: *docker_build_push

.CI_REGISTRY_IMAGE: &CI_REGISTRY_IMAGE
  stage: test
  before_script:
    - *docker_login_gitlab
    - *docker_pull
    - docker run -d -t --name test $CI_REGISTRY_IMAGE/$IMAGE

.test_drupal8ci: &test_drupal8ci
  <<: *CI_REGISTRY_IMAGE
  script:
    - docker exec test /scripts/run-tests.sh

.release: &release
  stage: release
  before_script:
    - docker login -u $RELEASE_USER -p $RELEASE_PASSWORD $RELEASE_REGISTRY
  script:
    - *docker_pull
    - docker tag $CI_REGISTRY_IMAGE/$IMAGE $RELEASE_IMAGE/$IMAGE
    - docker push $RELEASE_IMAGE/$IMAGE
    - docker push $RELEASE_IMAGE/drupal8ci:latest
  only:
    - master

################################################################################
# Jobs based on previous templates.
# Only variables need to be changed if needed.
################################################################################

before_script:
  - *docker_login_gitlab
  - *make_build

drupal8.6ci:
  <<: *build_image
  before_script:
    - *docker_login_gitlab
  variables:
    IMAGE: drupal8ci:8.6
    DIR: '8.6'

test:drupal8.6ci:
  <<: *test_drupal8ci
  variables:
    IMAGE: drupal8ci:8.6

release:drupal8.6ci:
  <<: *release
  variables:
    IMAGE: drupal8ci:8.6
