image: docker:stable

services:
  - docker:dind

stages:
  - build
  - test
  - release
  - build variant
  - test variant
  - release variant
  - build variant no drupal
  - test variant no drupal
  - release variant no drupal

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2
  RELEASE_REGISTRY: docker.io
  RELEASE_IMAGE: index.docker.io/$RELEASE_USER

################################################################################
# Templates to avoid repeat. A bit Xtrem here!
# https://docs.gitlab.com/ee/ci/yaml/#anchors
################################################################################

.docker_login_gitlab:
  - &docker_login_gitlab docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com

.docker_pull:
  - &docker_pull docker pull $CI_REGISTRY_IMAGE/$IMAGE || true

.docker_build_push:
  script: &docker_build_push
    - *docker_pull
    - docker build --compress --cache-from $RELEASE_IMAGE/$IMAGE --tag $CI_REGISTRY_IMAGE/$IMAGE $DIR
    - docker push $CI_REGISTRY_IMAGE/$IMAGE

.make_build:
  - &make_build apk --no-cache add make gettext && make build

.test_images: &test_images
  before_script:
    - *docker_login_gitlab
    - *docker_pull

.build_image: &build_image
  before_script:
    - *docker_login_gitlab
    - *make_build
  script: *docker_build_push
  only:
    - master
    - testing

.test_drupal8ci: &test_drupal8ci
  <<: *test_images
  script:
    - docker run --rm -t $CI_REGISTRY_IMAGE/$IMAGE /scripts/run-tests.sh
  only:
    - master
    - testing

.release: &release
  before_script:
    - docker login -u $RELEASE_USER -p $RELEASE_PASSWORD $RELEASE_REGISTRY
  script:
    - *docker_pull
    - docker tag $CI_REGISTRY_IMAGE/$IMAGE $RELEASE_IMAGE/$IMAGE
    - docker push $RELEASE_IMAGE/$IMAGE
  only:
    - master

################################################################################
# Jobs based on previous templates.
# Only variables need to be changed if needed.
################################################################################

before_script:
  - *docker_login_gitlab
  - *make_build

# Drupal 8.6

ci:
  <<: *build_image
  stage: build
  variables:
    IMAGE: drupal8ci:8.6
    DIR: '8.6/drupal'

t:ci:
  <<: *test_drupal8ci
  stage: test
  variables:
    IMAGE: drupal8ci:8.6

r:ci:
  <<: *release
  stage: release
  variables:
    IMAGE: drupal8ci:8.6

no-drupal:
  <<: *build_image
  stage: build variant
  variables:
    IMAGE: drupal8ci:8.6-no-drupal
    DIR: '8.6/no-drupal'

t:no-drupal:
  <<: *test_drupal8ci
  stage: test variant
  variables:
    IMAGE: drupal8ci:8.6-no-drupal

r:no-drupal:
  <<: *release
  stage: release variant
  variables:
    IMAGE: drupal8ci:8.6-no-drupal

selenium:
  <<: *build_image
  stage: build variant
  variables:
    IMAGE: drupal8ci:8.6-selenium
    DIR: '8.6/selenium'

t:selenium:
  <<: *test_drupal8ci
  stage: test variant
  variables:
    IMAGE: drupal8ci:8.6-selenium

r:selenium:
  <<: *release
  stage: release variant
  variables:
    IMAGE: drupal8ci:8.6-selenium

selenium-no-drupal:
  <<: *build_image
  stage: build variant no drupal
  variables:
    IMAGE: drupal8ci:8.6-selenium-no-drupal
    DIR: '8.6/selenium-no-drupal'

t:selenium-no-drupal:
  <<: *test_drupal8ci
  stage: test variant no drupal
  variables:
    IMAGE: drupal8ci:8.6-selenium-no-drupal

r:selenium-no-drupal:
  <<: *release
  stage: release variant no drupal
  variables:
    IMAGE: drupal8ci:8.6-selenium-no-drupal

# Drupal 8.7, waiting for Docker official image.
# https://github.com/docker-library/drupal/pull/150

.ci:
  <<: *build_image
  stage: build
  variables:
    IMAGE: drupal8ci:8.7
    DIR: '8.7/drupal'

.t:ci:
  <<: *test_drupal8ci
  stage: test
  variables:
    IMAGE: drupal8ci:8.7

.r:ci:
  <<: *release
  stage: release
  variables:
    IMAGE: drupal8ci:8.7

.no-drupal:
  <<: *build_image
  stage: build variant
  variables:
    IMAGE: drupal8ci:8.7-no-drupal
    DIR: '8.7/no-drupal'

.t:no-drupal:
  <<: *test_drupal8ci
  stage: test variant
  variables:
    IMAGE: drupal8ci:8.7-no-drupal

.r:no-drupal:
  <<: *release
  stage: release variant
  variables:
    IMAGE: drupal8ci:8.7-no-drupal

.selenium:
  <<: *build_image
  stage: build variant
  variables:
    IMAGE: drupal8ci:8.7-selenium
    DIR: '8.7/selenium'

.t:selenium:
  <<: *test_drupal8ci
  stage: test variant
  variables:
    IMAGE: drupal8ci:8.7-selenium

.r:selenium:
  <<: *release
  stage: release variant
  variables:
    IMAGE: drupal8ci:8.7-selenium

.selenium-no-drupal:
  <<: *build_image
  stage: build variant no drupal
  variables:
    IMAGE: drupal8ci:8.7-selenium-no-drupal
    DIR: '8.7/selenium-no-drupal'

.t:selenium-no-drupal:
  <<: *test_drupal8ci
  stage: test variant no drupal
  variables:
    IMAGE: drupal8ci:8.7-selenium-no-drupal

.r:selenium-no-drupal:
  <<: *release
  stage: release variant no drupal
  variables:
    IMAGE: drupal8ci:8.7-selenium-no-drupal